export { default as Home } from './home/Home.jsx'
export { default as Login } from './user/Login.jsx'
export { default as Signup } from './user/Signup.jsx'
export { default as RestaurantLogin } from './restaurant/Login.jsx'
export { default as RestaurantSignup } from './restaurant/Signup.jsx'
export { default as RestaurantForgot } from './restaurant/Forgot.jsx'
export { default as UserForgot } from './user/Forgot.jsx'
export { default as Orders} from './orders/Orders.jsx'
export {default as Create} from './create/Create.jsx'
export {default as AllRestaurant} from './restaurants/Restaurants.jsx'
export {default as SingleRestaurant} from './oneRestaurant/OneRestaurant.jsx'
export {default as SingleProduct} from './oneProduct/OneProduct.jsx'
export {default as Menu} from './menu/Menu.jsx'
export {default as Cart } from './cart/Cart.jsx'
export {default as AllProducts} from './products/Products.jsx'
export {default as EditProduct} from './edit/Edit.jsx'
export {default as PastOrders} from './pastOrders/PastOrders.jsx'
